/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const APIException = require('./APIException');
/**
 * Creates an instance of V3ErrorResponseException
 */
class V3ErrorResponseException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * Error message
         */
        this.message = null;

        /**
         * API Status / Metadata
         */
        this.status = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'message', realName: 'message' },
            { name: 'status', realName: 'status', type: 'V3Status' },
        ]);
    }
}

module.exports = V3ErrorResponseException;
