/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const ExpandEnum = {

    /**
     * TODO: Write general description for this element
     */
    ALL: 'All',

    /**
     * TODO: Write general description for this element
     */
    STOP: 'Stop',

    /**
     * TODO: Write general description for this element
     */
    ROUTE: 'Route',

    /**
     * TODO: Write general description for this element
     */
    RUN: 'Run',

    /**
     * TODO: Write general description for this element
     */
    DIRECTION: 'Direction',

    /**
     * TODO: Write general description for this element
     */
    DISRUPTION: 'Disruption',

};

module.exports = ExpandEnum;
