/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const HealthEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_0: 0,

    /**
     * TODO: Write general description for this element
     */
    ENUM_1: 1,

};

module.exports = HealthEnum;
