/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const RouteTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_0: 0,

    /**
     * TODO: Write general description for this element
     */
    ENUM_1: 1,

    /**
     * TODO: Write general description for this element
     */
    ENUM_2: 2,

    /**
     * TODO: Write general description for this element
     */
    ENUM_3: 3,

    /**
     * TODO: Write general description for this element
     */
    ENUM_4: 4,

};

module.exports = RouteTypeEnum;
