/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of V3BulkDeparturesRequest
 */
class V3BulkDeparturesRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.requests = this.constructor.getValue(obj.requests);
        this.dateUtc = this.constructor.getValue(obj.dateUtc || obj.date_utc);
        this.lookBackwards = this.constructor.getValue(obj.lookBackwards || obj.look_backwards);
        this.includeCancelled =
          this.constructor.getValue(obj.includeCancelled
     || obj.include_cancelled);
        this.expand = this.constructor.getValue(obj.expand);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'requests', realName: 'requests', array: true, type: 'V3StopDepartureRequest' },
            { name: 'dateUtc', realName: 'date_utc', isDateTime: true, dateTimeValue: 'rfc3339' },
            { name: 'lookBackwards', realName: 'look_backwards' },
            { name: 'includeCancelled', realName: 'include_cancelled' },
            { name: 'expand', realName: 'expand', array: true },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = V3BulkDeparturesRequest;
