/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of V3BulkDeparturesResponse
 */
class V3BulkDeparturesResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.responses = this.constructor.getValue(obj.responses);
        this.stops = this.constructor.getValue(obj.stops);
        this.routes = this.constructor.getValue(obj.routes);
        this.runs = this.constructor.getValue(obj.runs);
        this.directions = this.constructor.getValue(obj.directions);
        this.disruptions = this.constructor.getValue(obj.disruptions);
        this.status = this.constructor.getValue(obj.status);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            {
                name: 'responses',
                realName: 'responses',
                array: true,
                type: 'V3BulkDeparturesUpdateResponse',
            },
            { name: 'stops', realName: 'stops', type: 'V3BulkDeparturesStopResponse' },
            { name: 'routes', realName: 'routes', array: true, type: 'V3Route' },
            { name: 'runs', realName: 'runs', array: true, type: 'V3Run' },
            { name: 'directions', realName: 'directions', array: true, type: 'V3Direction' },
            { name: 'disruptions', realName: 'disruptions', type: 'V3Disruption' },
            { name: 'status', realName: 'status', type: 'V3Status' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = V3BulkDeparturesResponse;
