/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of V3Disruptions
 */
class V3Disruptions extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.general = this.constructor.getValue(obj.general);
        this.metroTrain = this.constructor.getValue(obj.metroTrain || obj.metro_train);
        this.metroTram = this.constructor.getValue(obj.metroTram || obj.metro_tram);
        this.metroBus = this.constructor.getValue(obj.metroBus || obj.metro_bus);
        this.regionalTrain = this.constructor.getValue(obj.regionalTrain || obj.regional_train);
        this.regionalCoach = this.constructor.getValue(obj.regionalCoach || obj.regional_coach);
        this.regionalBus = this.constructor.getValue(obj.regionalBus || obj.regional_bus);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'general', realName: 'general', array: true, type: 'V3Disruption' },
            { name: 'metroTrain', realName: 'metro_train', array: true, type: 'V3Disruption' },
            { name: 'metroTram', realName: 'metro_tram', array: true, type: 'V3Disruption' },
            { name: 'metroBus', realName: 'metro_bus', array: true, type: 'V3Disruption' },
            {
                name: 'regionalTrain',
                realName: 'regional_train',
                array: true,
                type: 'V3Disruption',
            },
            {
                name: 'regionalCoach',
                realName: 'regional_coach',
                array: true,
                type: 'V3Disruption',
            },
            { name: 'regionalBus', realName: 'regional_bus', array: true, type: 'V3Disruption' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = V3Disruptions;
