/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of V3DisruptionDirection
 */
class V3DisruptionDirection extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.routeDirectionId =
          this.constructor.getValue(obj.routeDirectionId
     || obj.route_direction_id);
        this.directionId = this.constructor.getValue(obj.directionId || obj.direction_id);
        this.directionName = this.constructor.getValue(obj.directionName || obj.direction_name);
        this.serviceTime = this.constructor.getValue(obj.serviceTime || obj.service_time);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'routeDirectionId', realName: 'route_direction_id' },
            { name: 'directionId', realName: 'direction_id' },
            { name: 'directionName', realName: 'direction_name' },
            { name: 'serviceTime', realName: 'service_time' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = V3DisruptionDirection;
