/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of V3OutletGeolocation
 */
class V3OutletGeolocation extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.outletDistance = this.constructor.getValue(obj.outletDistance || obj.outlet_distance);
        this.outletSlidSpid = this.constructor.getValue(obj.outletSlidSpid || obj.outlet_slid_spid);
        this.outletName = this.constructor.getValue(obj.outletName || obj.outlet_name);
        this.outletBusiness = this.constructor.getValue(obj.outletBusiness || obj.outlet_business);
        this.outletLatitude = this.constructor.getValue(obj.outletLatitude || obj.outlet_latitude);
        this.outletLongitude =
          this.constructor.getValue(obj.outletLongitude
     || obj.outlet_longitude);
        this.outletSuburb = this.constructor.getValue(obj.outletSuburb || obj.outlet_suburb);
        this.outletPostcode = this.constructor.getValue(obj.outletPostcode || obj.outlet_postcode);
        this.outletBusinessHourMon =
          this.constructor.getValue(obj.outletBusinessHourMon
     || obj.outlet_business_hour_mon);
        this.outletBusinessHourTue =
          this.constructor.getValue(obj.outletBusinessHourTue
     || obj.outlet_business_hour_tue);
        this.outletBusinessHourWed =
          this.constructor.getValue(obj.outletBusinessHourWed
     || obj.outlet_business_hour_wed);
        this.outletBusinessHourThur =
          this.constructor.getValue(obj.outletBusinessHourThur
     || obj.outlet_business_hour_thur);
        this.outletBusinessHourFri =
          this.constructor.getValue(obj.outletBusinessHourFri
     || obj.outlet_business_hour_fri);
        this.outletBusinessHourSat =
          this.constructor.getValue(obj.outletBusinessHourSat
     || obj.outlet_business_hour_sat);
        this.outletBusinessHourSun =
          this.constructor.getValue(obj.outletBusinessHourSun
     || obj.outlet_business_hour_sun);
        this.outletNotes = this.constructor.getValue(obj.outletNotes || obj.outlet_notes);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'outletDistance', realName: 'outlet_distance' },
            { name: 'outletSlidSpid', realName: 'outlet_slid_spid' },
            { name: 'outletName', realName: 'outlet_name' },
            { name: 'outletBusiness', realName: 'outlet_business' },
            { name: 'outletLatitude', realName: 'outlet_latitude' },
            { name: 'outletLongitude', realName: 'outlet_longitude' },
            { name: 'outletSuburb', realName: 'outlet_suburb' },
            { name: 'outletPostcode', realName: 'outlet_postcode' },
            { name: 'outletBusinessHourMon', realName: 'outlet_business_hour_mon' },
            { name: 'outletBusinessHourTue', realName: 'outlet_business_hour_tue' },
            { name: 'outletBusinessHourWed', realName: 'outlet_business_hour_wed' },
            { name: 'outletBusinessHourThur', realName: 'outlet_business_hour_thur' },
            { name: 'outletBusinessHourFri', realName: 'outlet_business_hour_fri' },
            { name: 'outletBusinessHourSat', realName: 'outlet_business_hour_sat' },
            { name: 'outletBusinessHourSun', realName: 'outlet_business_hour_sun' },
            { name: 'outletNotes', realName: 'outlet_notes' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = V3OutletGeolocation;
