/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of V3SearchResult
 */
class V3SearchResult extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.stops = this.constructor.getValue(obj.stops);
        this.routes = this.constructor.getValue(obj.routes);
        this.outlets = this.constructor.getValue(obj.outlets);
        this.status = this.constructor.getValue(obj.status);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'stops', realName: 'stops', array: true, type: 'V3ResultStop' },
            { name: 'routes', realName: 'routes', array: true, type: 'V3Route' },
            { name: 'outlets', realName: 'outlets', array: true, type: 'V3OutletGeolocation' },
            { name: 'status', realName: 'status', type: 'V3Status' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = V3SearchResult;
