/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of V3StopAccessibilityWheelchair
 */
class V3StopAccessibilityWheelchair extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.accessibleRamp = this.constructor.getValue(obj.accessibleRamp || obj.accessible_ramp);
        this.accessibleParking =
          this.constructor.getValue(obj.accessibleParking
     || obj.accessible_parking);
        this.accessiblePhone =
          this.constructor.getValue(obj.accessiblePhone
     || obj.accessible_phone);
        this.accessibleToilet =
          this.constructor.getValue(obj.accessibleToilet
     || obj.accessible_toilet);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'accessibleRamp', realName: 'accessible_ramp' },
            { name: 'accessibleParking', realName: 'accessible_parking' },
            { name: 'accessiblePhone', realName: 'accessible_phone' },
            { name: 'accessibleToilet', realName: 'accessible_toilet' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = V3StopAccessibilityWheelchair;
