/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of V3StopAccessibility
 */
class V3StopAccessibility extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.lighting = this.constructor.getValue(obj.lighting);
        this.stairs = this.constructor.getValue(obj.stairs);
        this.escalator = this.constructor.getValue(obj.escalator);
        this.lifts = this.constructor.getValue(obj.lifts);
        this.hearingLoop = this.constructor.getValue(obj.hearingLoop || obj.hearing_loop);
        this.tactileTiles = this.constructor.getValue(obj.tactileTiles || obj.tactile_tiles);
        this.wheelchair = this.constructor.getValue(obj.wheelchair);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'lighting', realName: 'lighting' },
            { name: 'stairs', realName: 'stairs' },
            { name: 'escalator', realName: 'escalator' },
            { name: 'lifts', realName: 'lifts' },
            { name: 'hearingLoop', realName: 'hearing_loop' },
            { name: 'tactileTiles', realName: 'tactile_tiles' },
            { name: 'wheelchair', realName: 'wheelchair', type: 'V3StopAccessibilityWheelchair' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = V3StopAccessibility;
