/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';


const Configuration = {
    // The base Uri for API calls
    BASEURI: 'http://timetableapi.ptv.vic.gov.au',

};

module.exports = Configuration;
