/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const V3RouteTypesResponse = require('../lib/Models/V3RouteTypesResponse');
const V3RouteResponse = require('../lib/Models/V3RouteResponse');
const V3OutletGeolocationResponse = require('../lib/Models/V3OutletGeolocationResponse');
const V3OutletResponse = require('../lib/Models/V3OutletResponse');
const V3OutletParameters = require('../lib/Models/V3OutletParameters');
const V3StopBase = require('../lib/Models/V3StopBase');
const V3DisruptionResponse = require('../lib/Models/V3DisruptionResponse');
const V3DisruptionsResponse = require('../lib/Models/V3DisruptionsResponse');
const V3DirectionsResponse = require('../lib/Models/V3DirectionsResponse');
const V3BulkDeparturesRouteDirectionResponse =
  require('../lib/Models/V3BulkDeparturesRouteDirectionResponse');
const V3Status = require('../lib/Models/V3Status');
const V3StopDepartureRequestRouteDirection =
  require('../lib/Models/V3StopDepartureRequestRouteDirection');
const V3DisruptionDirection = require('../lib/Models/V3DisruptionDirection');
const V3Direction = require('../lib/Models/V3Direction');
const V3DeparturesBroadParameters = require('../lib/Models/V3DeparturesBroadParameters');
const V3DeparturesResponse = require('../lib/Models/V3DeparturesResponse');
const V3Departure = require('../lib/Models/V3Departure');
const V3ResultStop = require('../lib/Models/V3ResultStop');
const V3Route = require('../lib/Models/V3Route');
const V3Run = require('../lib/Models/V3Run');
const V3VehiclePosition = require('../lib/Models/V3VehiclePosition');
const V3VehicleDescriptor = require('../lib/Models/V3VehicleDescriptor');
const V3Disruption = require('../lib/Models/V3Disruption');
const V3DisruptionRoute = require('../lib/Models/V3DisruptionRoute');
const V3DeparturesSpecificParameters = require('../lib/Models/V3DeparturesSpecificParameters');
const V3RouteDeparturesSpecificParameters =
  require('../lib/Models/V3RouteDeparturesSpecificParameters');
const V3BulkDeparturesRequest = require('../lib/Models/V3BulkDeparturesRequest');
const V3StopDepartureRequest = require('../lib/Models/V3StopDepartureRequest');
const V3BulkDeparturesResponse = require('../lib/Models/V3BulkDeparturesResponse');
const V3BulkDeparturesUpdateResponse = require('../lib/Models/V3BulkDeparturesUpdateResponse');
const V3BulkDeparturesStopResponse = require('../lib/Models/V3BulkDeparturesStopResponse');
const V3Disruptions = require('../lib/Models/V3Disruptions');
const V3Outlet = require('../lib/Models/V3Outlet');
const V3OutletGeolocationParameters = require('../lib/Models/V3OutletGeolocationParameters');
const V3OutletGeolocation = require('../lib/Models/V3OutletGeolocation');
const V3StoppingPattern = require('../lib/Models/V3StoppingPattern');
const V3RouteType = require('../lib/Models/V3RouteType');
const V3RunsResponse = require('../lib/Models/V3RunsResponse');
const V3RunResponse = require('../lib/Models/V3RunResponse');
const V3SearchParameters = require('../lib/Models/V3SearchParameters');
const V3SearchResult = require('../lib/Models/V3SearchResult');
const V3StopResponse = require('../lib/Models/V3StopResponse');
const V3StopDetails = require('../lib/Models/V3StopDetails');
const V3StopLocation = require('../lib/Models/V3StopLocation');
const V3StopGps = require('../lib/Models/V3StopGps');
const V3StopAmenityDetails = require('../lib/Models/V3StopAmenityDetails');
const V3StopAccessibility = require('../lib/Models/V3StopAccessibility');
const V3StopAccessibilityWheelchair = require('../lib/Models/V3StopAccessibilityWheelchair');
const V3StopsOnRouteResponse = require('../lib/Models/V3StopsOnRouteResponse');
const V3StopOnRoute = require('../lib/Models/V3StopOnRoute');
const V3StopsByDistanceResponse = require('../lib/Models/V3StopsByDistanceResponse');
const V3ErrorResponseException = require('../lib/Exceptions/V3ErrorResponseException');

const classMap = {
    V3RouteTypesResponse,
    V3RouteResponse,
    V3OutletGeolocationResponse,
    V3OutletResponse,
    V3OutletParameters,
    V3StopBase,
    V3DisruptionResponse,
    V3DisruptionsResponse,
    V3DirectionsResponse,
    V3BulkDeparturesRouteDirectionResponse,
    V3Status,
    V3StopDepartureRequestRouteDirection,
    V3DisruptionDirection,
    V3Direction,
    V3DeparturesBroadParameters,
    V3DeparturesResponse,
    V3Departure,
    V3ResultStop,
    V3Route,
    V3Run,
    V3VehiclePosition,
    V3VehicleDescriptor,
    V3Disruption,
    V3DisruptionRoute,
    V3DeparturesSpecificParameters,
    V3RouteDeparturesSpecificParameters,
    V3BulkDeparturesRequest,
    V3StopDepartureRequest,
    V3BulkDeparturesResponse,
    V3BulkDeparturesUpdateResponse,
    V3BulkDeparturesStopResponse,
    V3Disruptions,
    V3Outlet,
    V3OutletGeolocationParameters,
    V3OutletGeolocation,
    V3StoppingPattern,
    V3RouteType,
    V3RunsResponse,
    V3RunResponse,
    V3SearchParameters,
    V3SearchResult,
    V3StopResponse,
    V3StopDetails,
    V3StopLocation,
    V3StopGps,
    V3StopAmenityDetails,
    V3StopAccessibility,
    V3StopAccessibilityWheelchair,
    V3StopsOnRouteResponse,
    V3StopOnRoute,
    V3StopsByDistanceResponse,
    V3ErrorResponseException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
