/**
 * PTVTimetableAPIVersion3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const _request = require('../Http/Client/RequestClient');
const _configuration = require('../configuration');
const _apiHelper = require('../APIHelper');
const _baseController = require('./BaseController');

class DeparturesController {
    /**
     * View departures for all routes from a stop
     *
     * @param {RouteType63Enum} routeType Number identifying transport mode; values returned via
     * RouteTypes API
     * @param {int} stopId Identifier of stop; values returned by Stops API
     * @param {array} platformNumbers (optional) Filter by platform number at stop
     * @param {int} directionId (optional) Filter by identifier of direction of travel; values
     * returned by Directions API - /v3/directions/route/{route_id}
     * @param {bool} lookBackwards (optional) Indicates if filtering runs (and their departures) to
     * those that arrive at destination before date_utc (default =
     * false). Requires max_results &gt; 0.
     * @param {bool} gtfs (optional) Indicates that stop_id parameter will accept "GTFS stop_id"
     * data
     * @param {dateTime} dateUtc (optional) Filter by the date and time of the request (ISO 8601
     * UTC format) (default = current date and time)
     * @param {int} maxResults (optional) Maximum number of results returned
     * @param {bool} includeCancelled (optional) Indicates if cancelled services (if they exist)
     * are returned (default = false) - metropolitan train only
     * @param {array} expand (optional) List objects to be returned in full (i.e. expanded) -
     * options include: all, stop, route, run, direction, disruption
     * @param {string} token (optional) Please ignore
     * @param {string} devid (optional) Your developer id
     * @param {string} signature (optional) Authentication signature for request
     *
     * @callback    The callback function that returns response from the API call
     *
     * @returns {Promise}
     */
    static getDeparturesGetForStop(routeType,
        stopId,
        platformNumbers,
        directionId,
        lookBackwards,
        gtfs,
        dateUtc,
        maxResults,
        includeCancelled,
        expand,
        token,
        devid,
        signature,
        callback) {
        // create empty callback if absent
        const _callback = typeof callback === 'function' ? callback : () => undefined;

        // prepare query string for API call
        const _baseUri = _configuration.BASEURI;

        let _queryBuilder = `${_baseUri}${'/v3/departures/route_type/{route_type}/stop/{stop_id}'}`;

        // process template parameters
        _queryBuilder = _apiHelper.appendUrlWithTemplateParameters(_queryBuilder, {
            route_type: (routeType !== null) ? routeType : null,
            stop_id: stopId,
        });

        // process query parameters
        _queryBuilder = _apiHelper.appendUrlWithQueryParameters(_queryBuilder, {
            platform_numbers: platformNumbers,
            direction_id: directionId,
            look_backwards: lookBackwards,
            gtfs,
            date_utc: _apiHelper.stringifyDateTime(dateUtc, 'rfc3339'),
            max_results: maxResults,
            include_cancelled: includeCancelled,
            expand: (expand !== null) ? expand : null,
            token,
            devid,
            signature,
        });

        // validate and preprocess url
        const _queryUrl = _apiHelper.cleanUrl(_queryBuilder);

        // prepare headers
        const _headers = {
            accept: 'application/json',
        };

        // construct the request
        const _options = {
            queryUrl: _queryUrl,
            method: 'GET',
            headers: _headers,
        };

        // build the response processing.
        return new Promise((_fulfill, _reject) => {
            _request(_options, (_error, _response, _context) => {
                let errorResponse;
                let response = '';
                if (_context.response.body) {
                    response = JSON.parse(_context.response.body);
                }
                if (_error) {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                    let parsed = JSON.parse(_response.body);
                    parsed = _baseController.getObjectMapper().mapObject(parsed, 'V3DeparturesResponse');
                    _callback(null, parsed, _context);
                    _fulfill(parsed);
                } else if (_response.statusCode === 400) {
                    const mappedObject = _baseController.getObjectMapper()
                        .mapObject(response, 'V3ErrorResponseException');
                    mappedObject.reason = 'Invalid Request';
                    mappedObject.context = _context;
                    const _err = { errorMessage: 'Invalid Request', errorCode: 400, errorResponse: mappedObject };
                    _callback(_err, null, _context);
                    _reject(_err);
                } else if (_response.statusCode === 403) {
                    const mappedObject = _baseController.getObjectMapper()
                        .mapObject(response, 'V3ErrorResponseException');
                    mappedObject.reason = 'Access Denied';
                    mappedObject.context = _context;
                    const _err = { errorMessage: 'Access Denied', errorCode: 403, errorResponse: mappedObject };
                    _callback(_err, null, _context);
                    _reject(_err);
                } else {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                }
            });
        });
    }
    /**
     * View departures for a specific route from a stop
     *
     * @param {RouteType63Enum} routeType Number identifying transport mode; values returned via
     * RouteTypes API
     * @param {int} stopId Identifier of stop; values returned by Stops API
     * @param {string} routeId Identifier of route; values returned by Routes API - v3/routes
     * @param {int} directionId (optional) Filter by identifier of direction of travel; values
     * returned by Directions API - /v3/directions/route/{route_id}
     * @param {bool} lookBackwards (optional) Indicates if filtering runs (and their departures) to
     * those that arrive at destination before date_utc (default =
     * false). Requires max_results &gt; 0.
     * @param {bool} gtfs (optional) Indicates that stop_id parameter will accept "GTFS stop_id"
     * data
     * @param {dateTime} dateUtc (optional) Filter by the date and time of the request (ISO 8601
     * UTC format) (default = current date and time)
     * @param {int} maxResults (optional) Maximum number of results returned
     * @param {bool} includeCancelled (optional) Indicates if cancelled services (if they exist)
     * are returned (default = false) - metropolitan train only
     * @param {array} expand (optional) List objects to be returned in full (i.e. expanded) -
     * options include: all, stop, route, run, direction, disruption
     * @param {string} token (optional) Please ignore
     * @param {string} devid (optional) Your developer id
     * @param {string} signature (optional) Authentication signature for request
     *
     * @callback    The callback function that returns response from the API call
     *
     * @returns {Promise}
     */
    static getDeparturesGetForStopAndRoute(routeType,
        stopId,
        routeId,
        directionId,
        lookBackwards,
        gtfs,
        dateUtc,
        maxResults,
        includeCancelled,
        expand,
        token,
        devid,
        signature,
        callback) {
        // create empty callback if absent
        const _callback = typeof callback === 'function' ? callback : () => undefined;

        // prepare query string for API call
        const _baseUri = _configuration.BASEURI;

        let _queryBuilder = `${_baseUri}${'/v3/departures/route_type/{route_type}/stop/{stop_id}/route/{route_id}'}`;

        // process template parameters
        _queryBuilder = _apiHelper.appendUrlWithTemplateParameters(_queryBuilder, {
            route_type: (routeType !== null) ? routeType : null,
            stop_id: stopId,
            route_id: routeId,
        });

        // process query parameters
        _queryBuilder = _apiHelper.appendUrlWithQueryParameters(_queryBuilder, {
            direction_id: directionId,
            look_backwards: lookBackwards,
            gtfs,
            date_utc: _apiHelper.stringifyDateTime(dateUtc, 'rfc3339'),
            max_results: maxResults,
            include_cancelled: includeCancelled,
            expand: (expand !== null) ? expand : null,
            token,
            devid,
            signature,
        });

        // validate and preprocess url
        const _queryUrl = _apiHelper.cleanUrl(_queryBuilder);

        // prepare headers
        const _headers = {
            accept: 'application/json',
        };

        // construct the request
        const _options = {
            queryUrl: _queryUrl,
            method: 'GET',
            headers: _headers,
        };

        // build the response processing.
        return new Promise((_fulfill, _reject) => {
            _request(_options, (_error, _response, _context) => {
                let errorResponse;
                let response = '';
                if (_context.response.body) {
                    response = JSON.parse(_context.response.body);
                }
                if (_error) {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                    let parsed = JSON.parse(_response.body);
                    parsed = _baseController.getObjectMapper().mapObject(parsed, 'V3DeparturesResponse');
                    _callback(null, parsed, _context);
                    _fulfill(parsed);
                } else if (_response.statusCode === 400) {
                    const mappedObject = _baseController.getObjectMapper()
                        .mapObject(response, 'V3ErrorResponseException');
                    mappedObject.reason = 'Invalid Request';
                    mappedObject.context = _context;
                    const _err = { errorMessage: 'Invalid Request', errorCode: 400, errorResponse: mappedObject };
                    _callback(_err, null, _context);
                    _reject(_err);
                } else if (_response.statusCode === 403) {
                    const mappedObject = _baseController.getObjectMapper()
                        .mapObject(response, 'V3ErrorResponseException');
                    mappedObject.reason = 'Access Denied';
                    mappedObject.context = _context;
                    const _err = { errorMessage: 'Access Denied', errorCode: 403, errorResponse: mappedObject };
                    _callback(_err, null, _context);
                    _reject(_err);
                } else {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                }
            });
        });
    }
}
module.exports = DeparturesController;
